### ISSUE TITLE
eroor opening Kirby panel

### ISSUE THREAD

**Issue by christr1** [bastianallgeier/kirbycms-panel#37]
this error occurs:
Warning: Cannot modify header information - headers already sent by (output started at /home/vhosts/buitenkader.info/httpdocs/site/config/config.php:1) in /home/vhosts/buitenkader.info/httpdocs/kirby/lib/kirby.php on line 47

**Comment by simonlayfield** [comment]
@rizkysyazuli I know this was some time ago, but would you have any insight in to the solution? Was it a permissions issue as cited in #53?

I have a redirect loop when visiting /panel on my VPS and it's killing me :/

Further details here: https://forum.getkirby.com/t/redirect-loop-because-of-rewriterules/1860/7

**Comment by bastianallgeier** [comment]
This is the old repository. Please use the current one for bug reports.
